### ISSUE TITLE
Bug? run over a sub-domain

### ISSUE THREAD

**Issue by ecosme38** [SWOTsimulator/swotsimulator#10]
I found the simulator fails with the modelbox option on and irregular grid because the model grid itself is not restricted, onyl the data. I solved the problem adding two lines:
model_data.vlon = model_data.vlon[model_data.model_index]
model_data.vlat = model_data.vlat[model_data.model_index]
around line 158 in run_simulator.py.
But I wonder why not using the selct_modelbox function?

**Comment by lgaultier** [comment]
Hi, 
It is corrected and pushed to the develop and master, thanks for pointing that out. 
I split the code into small function last year and wrote the select_modelbox but I did not have time to test all the functions thoroughly. I will check that as soon as possible. 
Lucile
