### ISSUE TITLE
example data are missing, how to get it ?

### ISSUE THREAD

**Issue by chenliangrs** [SWOTsimulator/swotsimulator#12]
This example data are not available under this link: http://swot.jpl.nasa.gov/science/resources/ :,, how can we get the address of swotsimulator_largedata.zip to download the data ? Thank you very much !

**Comment by lgaultier** [comment]
Hi, The swot jpl website has been modified and thus the link doesn't work anymore. 
I have informed the webmaster about this issue. I hope I will get an answer soon. Thanks for pointing that out. I will let you know as soon I have any update.

**Comment by lgaultier** [comment]
The link has been updated, data are now available at [https://swot.jpl.nasa.gov/files/SWOTsimulator/swotsimulator_largedata.zip].
