### ISSUE TITLE
Compatibility problem with numpy 1.14.0

### ISSUE THREAD

**Issue by SammyMetref** [SWOTsimulator/swotsimulator#13]
It seems that the new 1.14.0 numpy version does not allow the substraction of boolean anymore. When using the simulator this error appears: 

"TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead."

I tracked the problem to l.224 in the 'cart2spher' function of 'mod_tools.py', although it might happen elsewhere. 

I think we should either advise to use an earlier version of numpy in the simulator documentation (e.g. 1.13.3) or find a different formulation of the boolean subtraction. 

I stay available if need be to help in implementing either of these solutions or any other alternatives.

**Comment by lgaultier** [comment]
Hi Sammy, 
Thanks for spotting the bug, it is fixed and the simulator should work properly withn numpy 1.14.
Let me know if you encounter any issue
