### ISSUE TITLE
example data

### ISSUE THREAD

**Issue by LauraGomezNavarro** [SWOTsimulator/swotsimulator#14]
It looks like the data to run the example is no longer available.  The link in the README (https://swot.jpl.nasa.gov/files/SWOTsimulator/swotsimulator_largedata.zip) gives a 'File Not Found' message. 

Thanks!

**Comment by lgaultier** [comment]
Thanks for the information, I will contact the JPL and update the link as soon as possible.

**Comment by chaiheng753** [comment]
Hi Lucile Gaultier, 

I am trying to download the swotsimulator_largedata.zip but it still says "File not found (404 error)". Do you have an alternative link, e.g. Dropbox, where I can download the data to run the example? 

Thank you.

Heng
M2C, Université de Rouen Normandie

**Comment by lgaultier** [comment]
Hi, 
The link is indeed broken on NASA side, I will try to reach the personn in charge next week. 
Meanwhile you can download it from our ftp server: 
[www.oceandatalab.com/files/swot_inputs/input_fields.tar.xz](url)
Sorry for the inconvenience
Lucile

**Comment by lgaultier** [comment]
Hi, 
The link is fixed so everything is back to normal.
All the best
Lucile

**Comment by jkarstensen** [comment]
Hi - it looks like again the download for the data files is corrupt - can please fix that?
Thanks
