### ISSUE TITLE
AttributeError: 'str' object has no attribute 'shift_lon'

### ISSUE THREAD

**Issue by chaiheng753** [SWOTsimulator/swotsimulator#17]
Hi,

I am a new user of SWOT Simulator (since yesterday). I tried to run the example and got an error (last line) as follows. Can anyone please advise? Thank you in advance.

root@heng:/home/swotsimulator# python run.py ./example/params_example.py
Traceback (most recent call last):
  File "run.py", line 26, in <module>
    run_simulator.run_simulator(file_param)
  File "/home/swotsimulator/swotsimulator/run_simulator.py", line 74, in run_simulator
    mod_tools.initialize_parameters(p)
  File "/home/swotsimulator/swotsimulator/mod_tools.py", line 40, in initialize_parameters
    p.shift_lon = getattr(p, 'shift_lon', None)
AttributeError: 'str' object has no attribute 'shift_lon'

Heng
M2C, Universite de Rouen Normandie

**Comment by chaiheng753** [comment]
I have just noticed that I do not have the "params_example.txt" file.

**Comment by lgaultier** [comment]
Hi, 
The installation and running instructions are provided in the README file. 
Lucile
