### ISSUE TITLE
encoding problem

### ISSUE THREAD

**Issue by jinbow** [SWOTsimulator/swotsimulator#18]
I downloaded the newest version and try to run it but got the following error code. 

Traceback (most recent call last):
  File "run.py", line 25, in <module>
    import swotsimulator.run_simulator as run_simulator
  File "/home1/jwang23/projects/swot/swotsimulator/swotsimulator/run_simulator.py", line 226
SyntaxError: Non-ASCII character '\xc2' in file /home1/jwang23/projects/swot/swotsimulator/swotsimulator/run_simulator.py on line 226, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I am using python2.7

**Comment by lgaultier** [comment]
Python 2 is not supported anymore for the swotsimulator. 
It is working fine with Python 3.
