### ISSUE TITLE
add continuous integration?

### ISSUE THREAD

**Issue by rabernat** [SWOTsimulator/swotsimulator#20]
As discussed in #19, we are interested in trying swot simulator and also potentially proposing some changes to handle data that is not stored in netCDF files.

It's great that swotsimulator has a test suite! Have you considered using [travis-ci](https://travis-ci.org) to automatically run these tests on every branch and pull request? This is what most community open-source python projects do. It greatly enhances the potential for collaboration by giving everyone a clear view of whether or not a potential contribution validates against the test suite.

This and other best practices for python packages are outlined on the [pangeo website](http://pangeo.io/packages.html#guidelines-for-new-packages).

**Comment by lgaultier** [comment]
As mentionned in #19, you will be able to write plugins that format your data into xarray. The new version of the simulator will use this xarray data as inputs. I did not consider to use travis-ci so far as I am not sure it has any added value in the swotsimulator cases. I will check again the relevance of this tool.
