### ISSUE TITLE
rw_data.py: file naming conventions

### ISSUE THREAD

**Issue by mgangl** [SWOTsimulator/swotsimulator#22]
When running the simulator from the master branch with the example data, i saw errors looking for 
```
swotsimulator/example/input_fields/OREGON_0101.nc.nc
```

Note the duplicate .nc values. In order to produce data with the same files downloaded from nasa, i removed the ".nc" in the following line. I'm not sure if this is a bug or a configuration issue on my end.

https://github.com/SWOTsimulator/swotsimulator/blob/master/swotsimulator/rw_data.py#L1158

**Comment by lgaultier** [comment]
The files in the list_of_file.txt should not contain the extension anymore. The example list of file has been modified accordingly.
