### ISSUE TITLE
'ssh_true'

### ISSUE THREAD

**Issue by joseph-daddezio** [SWOTsimulator/swotsimulator#29]
Hello,
Sorry to bother. I worked on this all day and made no progress. 

Error:

/!\ Error occurred while processing grid /u/GoM_4dvar/SWOT-cal-val/model/OoT/raw/SWOT_OoT/swot_output/OoT_science_grid_p584.nc
  Traceback (most recent call last):
  
  File "/home/jmdaddez/anaconda3/lib/python3.8/site-packages/swotsimulator-3.10-py3.8.egg/swotsimulator/mod_parallel.py", line 153, in _operation_wrapper
    operation(msg_queue, *_args, **kwargs)
  
  File "/home/jmdaddez/anaconda3/lib/python3.8/site-packages/swotsimulator-3.10-py3.8.egg/swotsimulator/run_simulator.py", line 497, in worker_method_swot
    create = mod.create_SWOTlikedata(cycle, list_file, modelbox,
  
  File "/home/jmdaddez/anaconda3/lib/python3.8/site-packages/swotsimulator-3.10-py3.8.egg/swotsimulator/mod_run.py", line 325, in create_SWOTlikedata
    model_step.read_var(index=model_data.model_index)
  
  **File "/home/jmdaddez/anaconda3/lib/python3.8/site-packages/swotsimulator-3.10-py3.8.egg/swotsimulator/rw_data.py", line 1166, in read_var
    self.input_var['ssh_true'] = self.input_var['ssh_true']*self.SSH_factor
  
KeyError: 'ssh_true'**

It looks like it's going inside rw_data.py on line 1153 and trying to run the loop. No matter what I assign as my 'var' and/or 'ssh_true' in the params.py file, it skips over the loop right to line 1166 where it fails because it didn't do anything (leaving the input_var dictionary empty). It should initialize in __init__ starting on line 1116 where it should at least have one entry for the input_var_list (ssh_true).

Not sure what is going on. 

params.py file attached. Bad installation?

Joseph
[params.py.pdf](https://github.com/SWOTsimulator/swotsimulator/files/6651233/params.py.pdf)

**Comment by lgaultier** [comment]
Hi Joseph, 
Your parameter file seems weird, You can send me one model file and your parameter file (as a py module this time) by email so that I can check. In the mean time, there is an updated version of the SWOTsimulator here: [https://github.com/CNES/swot_simulator](https://github.com/CNES/swot_simulator)
It runs faster on super computer, has an updated budget error but is more difficult to set up. 
I can give you a hand to start using it if necessary.
Lucile

**Comment by joseph-daddezio** [comment]
Thanks for the quick response, Lucile :)

I'll go grab the latest version and give it a go. I'll email you directly if I have any issues. Thanks!

Joseph
