### ISSUE TITLE
example data missing

### ISSUE THREAD

**Issue by ezaron** [SWOTsimulator/swotsimulator#6]
Greetings swotsimulator developers,
I downloaded and installed the package according to the documentation, but when I tried to run the example, the ./example/input_fields directory was missing. I am checking the old sourceforge page to see if the example files are over there.
All the best,
Ed

**Comment by lgaultier** [comment]
Hi ed, 
Thanks for pointing that out. Actually we had to remove the example data as we can't (and don't want to) git data that are too large. This data are available under this link: http://swot.jpl.nasa.gov/science/resources/ : click on swotsimulator_largedata.zip to download the data, then unzip the file and copy everything from the unzipped directory into example/input_field. I am going to update the readme file and the wiki right away to inform users about this fact.
Lucile
