### ISSUE TITLE
Fast-sampling orbit at the wrong place in New Caledonia region ?

### ISSUE THREAD

**Issue by serazing** [SWOTsimulator/swotsimulator#8]
I have tested the fast sampling orbit from the swot simulator and it does not seem to sample the same region as I was expected. In the following, I compare the output from the SWOT simulator and the orbit from the KML file available on AVISO: both swaths are inconsistent  !

Do you have any idea why I get this result ?

## SSH output from NEMO 1/12° 
Contours are the SSH field from the model. The black curves denote the fast-sampling orbit, plotted from the KML file available on AVISO.
![ssh_nc](https://cloud.githubusercontent.com/assets/19403647/21228779/614e27b2-c2df-11e6-9431-d049ad1c671a.png)

## SSH output from the SWOT simulator using the fast sampling orbit  
Here is the result of the SWOT simulator performed on the previous snapshot.
![swot_nc](https://cloud.githubusercontent.com/assets/19403647/21228784/675d880a-c2df-11e6-8dbc-87c5a0e9af67.png)

**Comment by lgaultier** [comment]
Thanks for pointing that out, There has been an update of the fast sampling orbit. It will be updated today. I willl close the ticket when it is done and tested
Lucile

**Comment by jinbow** [comment]
Thanks to Guillaume for noting this. Lucile, is the data in the simulator here or KML outdated?

**Comment by lgaultier** [comment]
Two new orbit files have been added, you should now use ephem_calval_june2015_ell.txt as the orbit file.
Modification has been tested in branch feature/update_orbit and merged into branches develop and master. Let me know if you have any issue with the modification
Lucile

**Comment by jinbow** [comment]
Hi Lucile, should we add reference about the data? What is the source?
