### ISSUE TITLE
Running the simulator without the nadir option

### ISSUE THREAD

**Issue by ecosme38** [SWOTsimulator/swotsimulator#9]
Hi, it looks like the simulator cannot be run without the option "nadir = False". Several variables are defined only under the "nadir=True" condition, then used even with nadir set to False. If a SWOT simulator wizard could fix that, it would be greatly appreciated.

**Comment by lgaultier** [comment]
Hi, 
The bug is fixed and merged in the develop and master branch, thank you for reporting it. Let me know if it is not working as expected. 
The SWOT simulator wizard
